apiVersion: apps/v1
kind: Deployment
metadata:
  name: $app_name
  labels:
    app: $app_name
spec:
  replicas: $k8s_replicas
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: $app_name
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: $app_name
    spec:
      imagePullSecrets:
        - name: $DOCKER_PULL_SECRET
      volumes:
        - name: application-db-config
          configMap:
            name: $DATABASE_INI
            items:
              - key: database.ini
                path: database.ini
      containers:
        - name: $app_name
          image: $IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: $PORT
          volumeMounts:
            - name: application-db-config
              mountPath: /home/appuser/database.ini
              subPath: database.ini
              readOnly: true
            - name: cache-volume
              mountPath: /home/appuser/mzId_convertor_temp

---
apiVersion: v1
kind: Service
metadata:
  name: $app_name-service
spec:
  selector:
    app: $app_name
  ports:
    - protocol: TCP
      port: $PORT
      targetPort: $PORT
      nodePort: $node_port
  type: NodePort
